---
- name: Add SSH key to authorized_keys
  hosts: all
  become: true
  tasks:
    - name: Add SSH key to authorized_keys
      authorized_key:
        user: username
        state: present
        key: "somekey"
